src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the product to the contact through discount object</description>
        <label>Product</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discount__c.object
<CustomObject>
    <description>The object is used to set discounts for specific customer/groups of customers</description>
    <fields>
        <fullName>Product__c</fullName>
        <description>This field is used to specify the product to which the discount applied</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field stores the reason for the discount</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Christmas discount</fullName>
                </value>
                <value>
                    <fullName>Employee</fullName>
                </value>
                <value>
                    <fullName>Long contract</fullName>
                </value>
                <value>
                    <fullName>Personal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This object is used to store information about the product</description>
    <fields>
        <fullName>Country__c</fullName>
        <description>Defines the country for which prices are applied</description>
        <label>Country</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>Contains country codes</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/TestDataHelper.cls
/**
 * Name: Test Data Helper
 * Description: This class is used to create a basic version of the object populating only required fields
 * IMPORTANT! Don't populate non-required fields in this class. All functionality specific fields should be populated in the respective test class
 */
public with sharing class TestDataHelper {

	public static Contact getContact(String lastName, Boolean isInsert) {

		Contact singleContact = new Contact();
		singleContact.LastName = lastName;
		//all required fields should be populated here

		if(isInsert) {
			insert singleContact;
		}

		return singleContact;
	}

	public static Product__c getProduct(String name, Boolean isInsert) {

		Product__c product = new Product__c();
		product.Name = name;
		product.Country__c = ConstantsClass.COUNTRY_FR;
		//all required fields should be populated here

		if(isInsert) {
			insert product;
		}

		return product;
	}

	public static Discount__c getDiscount(String discountType, Product__c product, Boolean isInsert) {

		Discount__c discount = new Discount__c();
		discount.Type__c = discountType;
		discount.Product__c = product?.Id;
		//all required fields should be populated here

		if(isInsert) {
			insert discount;
		}

		return discount;
	}
}