src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>This field contains an unique identifier for the record from the external system</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field stores the country of the customer</description>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the product to the contact through discount object</description>
        <label>Product</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discount__c.object
<CustomObject>
    <description>The object is used to set discounts for specific customer/groups of customers</description>
    <fields>
        <fullName>ATM_Fee_In_Other_Currencies__c</fullName>
        <formula>Product__r.ATM_Fee_In_Other_Currencies__c * (1 - ATM_Fee_In_Other_Currencies_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ATM Fee In Other Currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <formula>Product__r.Card_Replacement_Cost__c * (1 -  Card_Replacement_Cost_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <formula>Product__r.Cost_Per_Calendar_Month__c * (1 -  Cost_Per_Calendar_Month_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>This field is used to specify the product to which the discount applied</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This object is used to store information about the product</description>
    <fields>
        <fullName>ATM_Fee_In_Other_Currencies__c</fullName>
        <description>Fee in percent for ATM money withdrawal for other currencies</description>
        <label>ATM Fee In Other Currencies</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The cost for card replacement</description>
        <label>Card Replacement Cost</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <description>Cost per Calendar Month</description>
        <label>Cost Per Calendar Month</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>Contains country codes</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ContactsRESTService_TC.cls
@IsTest
private class ContactsRESTService_TC {

	private final static String CONTACT_LAST_NAME = 'TEST Customer';
	private final static String PRODUCT_NAME = 'Standard';
	private final static Decimal COST_PER_MONTH = 10;
	private final static Decimal ATM_FEE_OTHER_CURRENCIES = 0.05;
	private final static Decimal CARD_REPLACEMENT_COST = 7;
	private final static String DUMMY_EXTERNAL_ID = 'abc';
	private final static String DUMMY_NON_EXISTING_EXTERNAL_ID = '123';
	private final static String DUMMY_URL = 'http://dummy.com';

	@TestSetup
	static void setup() {

		Product__c product = TestDataHelper.getProduct(PRODUCT_NAME, false);
		product.Cost_Per_Calendar_Month__c = COST_PER_MONTH;
		product.ATM_Fee_In_Other_Currencies__c = ATM_FEE_OTHER_CURRENCIES;
		product.Card_Replacement_Cost__c = CARD_REPLACEMENT_COST;
		insert product;

		Discount__c discount = TestDataHelper.getDiscount(ConstantsClass.DISCOUNT_TYPE_PERSONAL, product, true);

		Contact singleContact = TestDataHelper.getContact(CONTACT_LAST_NAME, false);
		singleContact.Product__c = discount.Id;
		singleContact.Home_Country__c = ConstantsClass.COUNTRY_FR;
		singleContact.External_Id__c = DUMMY_EXTERNAL_ID;
		insert singleContact;
	}

	@IsTest
	static void getCustomer_NoIdInRequest_Test() {

		RestContext.response = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = DUMMY_URL + '/';
		RestContext.request = request;

		Test.startTest();
		ContactsRESTService.getCustomer();
		Test.stopTest();

		System.assertEquals(ConstantsClass.RESPONSE_CODE_BAD_REQUEST, RestContext.response.statusCode);
		System.assertEquals(ContactsRESTService.ERROR_NO_ID_PROVIDED, String.valueOf(RestContext.response.responseBody.toString()));
	}

	@IsTest
	static void getCustomer_NoContactFound_Test() {

		RestContext.response = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = DUMMY_URL + '/' + DUMMY_NON_EXISTING_EXTERNAL_ID;
		RestContext.request = request;

		Test.startTest();
		ContactsRESTService.getCustomer();
		Test.stopTest();

		System.assertEquals(ConstantsClass.RESPONSE_CODE_NOT_FOUND, RestContext.response.statusCode);
		System.assertEquals(ContactsRESTService.ERROR_NO_CONTACT_FOUND, String.valueOf(RestContext.response.responseBody.toString()));
	}

	@IsTest
	static void getCustomer_SuccessResponse_Test() {

		RestContext.response = new RestResponse();
		RestRequest request = new RestRequest();
		request.requestURI = DUMMY_URL + '/' + DUMMY_EXTERNAL_ID;
		RestContext.request = request;

		Test.startTest();
		ContactsRESTService.getCustomer();
		Test.stopTest();

		System.assertEquals(ConstantsClass.RESPONSE_CODE_SUCCESS, RestContext.response.statusCode);
		ContactsRESTService.CustomerWrapper wrapper = (ContactsRESTService.CustomerWrapper)
				JSON.deserialize(String.valueOf(RestContext.response.responseBody.toString()), ContactsRESTService.CustomerWrapper.class);
		System.assertEquals(CONTACT_LAST_NAME, wrapper.customerName);
		System.assertEquals(PRODUCT_NAME, wrapper.productName);
		System.assertEquals(CARD_REPLACEMENT_COST, wrapper.cardReplacementCost);
		System.assertEquals(ATM_FEE_OTHER_CURRENCIES, wrapper.aTMFeeInOtherCountries);
		System.assertEquals(CARD_REPLACEMENT_COST, wrapper.cardReplacementCost);
		System.assertEquals(ConstantsClass.COUNTRY_FR, wrapper.country);
	}
}