src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field stores the country of the customer</description>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the product to the contact through discount object</description>
        <label>Product</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discount__c.object
<CustomObject>
    <description>The object is used to set discounts for specific customer/groups of customers</description>
    <fields>
        <fullName>ATM_Fee_In_Other_Currencies__c</fullName>
        <formula>Product__r.ATM_Fee_In_Other_Currencies__c * (1 - ATM_Fee_In_Other_Currencies_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ATM Fee In Other Currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <formula>Product__r.Card_Replacement_Cost__c * (1 -  Card_Replacement_Cost_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <formula>Product__r.Cost_Per_Calendar_Month__c * (1 -  Cost_Per_Calendar_Month_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Contains the value of the Products Name</description>
        <formula>Product__r.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>This field is used to specify the product to which the discount applied</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This object is used to store information about the product</description>
    <fields>
        <fullName>ATM_Fee_In_Other_Currencies__c</fullName>
        <description>Fee in percent for ATM money withdrawal for other currencies</description>
        <label>ATM Fee In Other Currencies</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <description>The cost for card replacement</description>
        <label>Card Replacement Cost</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <description>Cost per Calendar Month</description>
        <label>Cost Per Calendar Month</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>Contains country codes</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ContactsRESTService.cls
/**
 * Name: Contacts REST Service
 * Description: This class is used by external systems to perform operations on the Contact object
 */
@RestResource(UrlMapping='/customers/*')
global with sharing class ContactsRESTService {

	@TestVisible
	private static final String ERROR_NO_CONTACT_FOUND = 'No Contact found by given external Id.'; //error messages specific to the functionality are stored in the class responsible for the functionality
	@TestVisible
	private static final String ERROR_NO_ID_PROVIDED = 'External Id is not provided/found in the request.';

	@HttpGet
	global static void getCustomer() {

		RestRequest req = RestContext.request;
		RestResponse res = RestContext.response;
		String errorMessage;
		CustomerWrapper wrapper = new CustomerWrapper();

		try {

			String externalId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1); //get the external id from the URI

			if (String.isBlank(externalId)) {

				res.statusCode = ConstantsClass.RESPONSE_CODE_BAD_REQUEST;
				errorMessage = ERROR_NO_ID_PROVIDED;
			} else {

				List<Contact> contacts = ContactSelector.getContactsByExternalId(externalId);

				if (contacts.isEmpty()) {    //external Id is unique so the system will find either one or none contacts

					res.statusCode = ConstantsClass.RESPONSE_CODE_NOT_FOUND;
					errorMessage = ERROR_NO_CONTACT_FOUND;
				} else {

					Contact singleContact = contacts[0];
					Discount__c product = singleContact.Product__r;

					wrapper.customerName = singleContact.Name;
					wrapper.productName = product?.Product_Name__c;
					wrapper.cardReplacementCost = product?.Card_Replacement_Cost__c; //cost is returned with already applied discount
					wrapper.aTMFeeInOtherCountries = product?.ATM_Fee_In_Other_Currencies__c;
					wrapper.costPerCalendarMonth = product?.Cost_Per_Calendar_Month__c;
					wrapper.country = singleContact?.Home_Country__c;

					res.statusCode = ConstantsClass.RESPONSE_CODE_SUCCESS;
				}
			}
		} catch (Exception exc) {

			res.statusCode = ConstantsClass.RESPONSE_CODE_INTERNAL_ERROR;
			errorMessage = ConstantsClass.ERROR_MESSAGE_UNHANDLED;
			// todo Exception should be logged here to the internal or external system, depending on the requirements
		}

		res.responseBody = Blob.valueOf(String.isBlank(errorMessage) ? JSON.serialize(wrapper) : errorMessage);
	}

	@TestVisible
	class CustomerWrapper {

		@TestVisible
		String customerName;
		@TestVisible
		String productName;
		@TestVisible
		String country;
		@TestVisible
		Decimal costPerCalendarMonth;
		@TestVisible
		Decimal aTMFeeInOtherCountries;
		@TestVisible
		Decimal cardReplacementCost;
	}
}