src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>This field contains an unique identifier for the record from the external system</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>This field stores the country of the customer</description>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field links the product to the contact through discount object</description>
        <label>Product</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Discount__c.object
<CustomObject>
    <description>The object is used to set discounts for specific customer/groups of customers</description>
    <fields>
        <fullName>ATM_Fee_In_Other_Currencies__c</fullName>
        <formula>Product__r.ATM_Fee_In_Other_Currencies__c * (1 - ATM_Fee_In_Other_Currencies_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ATM Fee In Other Currencies</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Card_Replacement_Cost__c</fullName>
        <formula>Product__r.Card_Replacement_Cost__c * (1 -  Card_Replacement_Cost_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Card Replacement Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Per_Calendar_Month__c</fullName>
        <formula>Product__r.Cost_Per_Calendar_Month__c * (1 -  Cost_Per_Calendar_Month_Discount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cost Per Calendar Month</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <description>Contains the value of the Products Name</description>
        <formula>Product__r.Name</formula>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>This field is used to specify the product to which the discount applied</description>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Discounts</relationshipLabel>
        <relationshipName>Discounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Discount</label>
    <nameField>
        <displayFormat>D-{0000000}</displayFormat>
        <label>Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <description>This object is used to store information about the product</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Country.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <description>Contains country codes</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

src/classes/ContactSelector.cls
/**
 * Name: Contact Selector
 * Description: This class is used to get Contact records from the DB
 */
public with sharing class ContactSelector {

	public static List<Contact> getContactsByExternalId(String externalId) {

		return [
				SELECT Name,
						Home_Country__c,
						Product__r.Product_Name__c,
						Product__r.ATM_Fee_In_Other_Currencies__c,
						Product__r.Cost_Per_Calendar_Month__c,
						Product__r.Card_Replacement_Cost__c
				FROM Contact
				WHERE External_Id__c = :externalId
				WITH SECURITY_ENFORCED
		];
	}
}